#!/usr/bin/env python3
"""Generate the three firmware headers from the SAME test windows, so the
feature-vector test (test_vectors.h) and the raw-window FFT test (raw_vectors.h)
use identical data:

  firmware/test_vectors.h  one TEST window per class, 128 standardized features
  firmware/raw_vectors.h   the matching raw 1024-sample windows as 12-bit ADC
                           counts (what the board's FFT path consumes)
  firmware/norm.h          FE_WIN/HOP/NBINS + train-only mean/std

Run after train.py. Usage: python make_vectors.py    Apache-2.0."""
import json, numpy as np
from pathlib import Path
from preprocess import de_signal, adc_quantize, WIN, HOP, NBINS

ROOT = Path(__file__).parent
FW = ROOT.parent / "firmware"
d = np.load(ROOT / "data" / "features.npz")
X, y, split, src, start = d["X"], d["y"], d["split"], d["src"], d["start"]
classes = json.loads((ROOT / "data" / "classes.json").read_text())
files = json.loads((ROOT / "data" / "files.json").read_text())
norm = json.loads((ROOT / "data" / "norm.json").read_text())
mean, std = norm["mean"], norm["std"]
Xn = (X - mean) / std
rng = np.random.default_rng(7)

# pick one TEST window per class (deterministic)
picks = []
for ci in range(len(classes)):
    pool = np.where((y == ci) & (split == 1))[0]
    picks.append(int(rng.choice(pool)))

# --- test_vectors.h (standardized features) ---
tv = ['/* Generated by make_vectors.py from TEST windows. Do not edit. */',
      '#pragma once', '',
      f'constexpr int kNumTests = {len(classes)};',
      'constexpr int kFeatureDim = 128;',
      'const char* const kTestLabels[kNumTests] = {%s};' % ', '.join('"%s"' % c for c in classes),
      'const int kTestExpected[kNumTests] = {%s};' % ', '.join(str(i) for i in range(len(classes))),
      'const float kTestVectors[kNumTests][kFeatureDim] = {']
for idx in picks:
    tv.append('  {%s},' % ', '.join('%.6ff' % v for v in Xn[idx]))
tv += ['};', '']
(FW / "test_vectors.h").write_text('\n'.join(tv))

# --- raw_vectors.h (matching raw windows as 12-bit ADC counts) ---
rv = ['/* Generated by make_vectors.py. Raw 1024-sample TEST windows as 12-bit',
      '   ADC counts (fixed +/-8g full-scale). Board runs FFT->features->classify',
      '   on these; they match test_vectors.h one-for-one. Do not edit. */',
      '#pragma once', '',
      f'constexpr int kNumRaw = {len(classes)};',
      'constexpr int kRawLen = 1024;',
      'const char* const kRawLabels[kNumRaw] = {%s};' % ', '.join('"%s"' % c for c in classes),
      'const int kRawExpected[kNumRaw] = {%s};' % ', '.join(str(i) for i in range(len(classes))),
      'const float kRawWindows[kNumRaw][kRawLen] = {']
sig_cache = {}
for idx in picks:
    fi, s = int(src[idx]), int(start[idx])
    if fi not in sig_cache:
        sig_cache[fi] = adc_quantize(de_signal(ROOT / "data" / "cwru" / files[fi]))
    win = sig_cache[fi][s:s + WIN]
    rv.append('  {%s},' % ', '.join('%.1ff' % v for v in win))   # counts (integers)
rv += ['};', '']
(FW / "raw_vectors.h").write_text('\n'.join(rv))

# --- norm.h ---
nh = ['/* Generated by make_vectors.py from ml/data/norm.json. Do not edit.',
      '   Feature standardization (train-only stats) + windowing params. */',
      '#pragma once',
      f'#define FE_WIN   {WIN}',
      f'#define FE_HOP   {HOP}',
      f'#define FE_NBINS {NBINS}',
      f'#define FE_MEAN  {mean:.8f}f',
      f'#define FE_STD   {std:.8f}f', '']
(FW / "norm.h").write_text('\n'.join(nh))

print(f"wrote test_vectors.h, raw_vectors.h ({len(classes)} matched windows), norm.h")
print(f"mean={mean:.6f} std={std:.6f}")
