/* Generated by make_vectors.py from ml/data/norm.json. Do not edit.
   Feature standardization (train-only stats) + windowing params. */
#pragma once
#define FE_WIN   1024
#define FE_HOP   512
#define FE_NBINS 128
#define FE_MEAN  5.05457449f
#define FE_STD   1.73326898f
